[workspace]
members = ["crates/engram-types", "crates/engram-store", "crates/engram-ffi"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "Apache-2.0"

[patch.crates-io]
subprocess = { path = "vendor/subprocess" }
